const projectConstents = {
    PROJECT_START   : 'PROJECT_START',
    PROJECT_SUCCESS : 'PROJECT_SUCCESS',
    PROJECT_FAILED  : 'PROJECT_FAILED',
    PROJECT_DETAIL_START   : 'PROJECT_DETAIL_START',
    PROJECT_DETAIL_SUCCESS : 'PROJECT_DETAIL_SUCCESS',
    PROJECT_DETAIL_FAILED  : 'PROJECT_DETAIL_FAILED',
    PROJECT_CREATE_START   : 'PROJECT_CREATE_START',
    PROJECT_CREATE_SUCCESS : 'PROJECT_CREATE_SUCCESS',
    PROJECT_CREATE_FAILED  : 'PROJECT_CREATE_FAILED',
}

export default projectConstents;