const userConstents = {
    REGISTER_START   : 'REGISTER_START',
    REGISTER_SUCCESS : 'REGISTER_SUCCESS',
    REGISTER_FAILED  : 'REGISTER_FAILED',
    REGISTER_ERROR   : 'REGISTER_ERROR',
    USER_ACTIVATE    : 'USER_ACTIVATE',
    LOGIN_START      : 'LOGIN_START',
    LOGIN_SUCCESS    : 'LOGIN_SUCCESS',
    LOGIN_FAILED     : 'LOGIN_FAILED',
    LOGIN_ERROR      : 'LOGIN_ERROR', 
    DASHBOARD_START  : 'DASHBOARD_START',
    DASHBOARD_SUCCESS : 'DASHBOARD_SUCCESS',
    DASHBOARD_ERROR  : 'DASHBOARD_ERROR'
}

export default userConstents;